name = "formalizedProblems"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["formalizedProblems","ProblemExtraction"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.cdot = true


[[require]]

name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.0"

[[lean_lib]]
name = "formalizedProblems"

[[lean_lib]]
name = "ProblemExtraction"